### ISSUE TITLE
Update dep to v0.2.1 mainnet rewards

### ISSUE THREAD

**Issue by bb111189** [alt-research/wizard-templates#15]
**User story**
User stories are often expressed in a simple sentence, structured as follows: 'As a PERSONA, I want to GOAL_DESCRIPTION, so that CUSTOMER_VALUE_DESCRIPTION.' Alternatively for 

We may be on v0.2.1-holesky rewards. should update to latest release,  v0.2.1 mainnet rewards

**Actions**
- [ ] An action item list describing the work to be done
- [ ] Link to all of the related tasks needed to complete the feature. See the [tasks](https://github.com/Layr-Labs/docs/blob/949bd6b4ddd0ef08880c6775c2d9a6222e2e7eb3/.github/ISSUE_TEMPLATE/task.md) template.
- [ ] Include everything in the definition of done e.g. unit tests and documentation

**Acceptance criteria**
Acceptance criteria are the requirements that need to be met in order to mark a user story as complete. For example, if your user story is, "As a New Relic customer, I want to know how to interpret AI anomalies in order to monitor my site and protect myself against incidents," then the acceptance criteria would be: "A complete and published doc describing AI anomalies," and all related quality checks.

**Comment by neutiyoo** [comment]
Currently we use https://github.com/Layr-Labs/eigenlayer-middleware/releases/tag/v0.2.1-mainnet-rewards since https://github.com/alt-research/wizard-templates/pull/11.

```
commit 74438b7915c35ca5a0d312654716160c2499169d (HEAD, tag: v0.2.1-mainnet-rewards)
```
